### PR TITLE
video post add VideoUrl and Duration field

### PR DESCRIPTION
**Pull request by jaggerwang**

### CODE REVIEW

**Comment by jasonpenny** [comment]
Thanks for your submission! It looks like you haven't signed the CLA yet

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by jaggerwang** [comment]
@jasonpenny done!

**Comment by jasonpenny** [comment]
Thanks!

**Pull request merged**
