### PR TITLE
Gofmt

### PR DESCRIPTION
**Pull request by ferhatelmas**

### CODE REVIEW

**Comment by foush** [comment]
👍

**Comment by defect** [comment]
Thanks @ferhatelmas! This looks good to me :) Have you signed the CLA and sent it our way? If not, please take a quick look at [CONTRIBUTING.md](https://github.com/tumblr/tumblr.go/blob/master/CONTRIBUTING.md) and let me know :)

**Comment by jasonpenny** [comment]
Thanks for your submission @ferhatelmas, I know this is from a while ago, but can you fix the merge conflict and sign the CLA?

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by ferhatelmas** [comment]
@jasonpenny signed and updated.

**Comment by jasonpenny** [comment]
👍

**Pull request merged**
